### ISSUE TITLE
Make C extension loading more predictable

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/Persistence#4]
This started as a comment in https://github.com/zopefoundation/Persistence/pull/3#issuecomment-274335086:

Persistence only works if you have all dependencies of it are either using C extensions or none of them are. If either persistent or ExtensionClass is missing the C extension, the Persistence C extension shouldn't be used.

Something similar applies to ExtensionClass and Acquisition.

**Comment by jamadden** [comment]
This may imply/include turning a C-level AttributeError into ImportError like what had to happen in BTrees: https://github.com/zopefoundation/BTrees/pull/55
