### ISSUE TITLE
Build / publish wheels on Appveyor

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/Persistence#8]
Checklist from https://github.com/zopefoundation/zope.proxy/issues/24:

- [x] a copy of `appveyor.yml` from `zope.interface` or similar
- [x] someone with an Appveyor account (e.g. @mgedmin ) to enable this project
- [x] encrypted PyPI upload credentials in the `appveyor.yml` (no change required from the copy in `zope.interface` if @mgedmin is the one who enables the Appveyor account)
- [x] grant **zope.wheelbuilder** PyPI rights
- [x] push the `appveyor.yml` commit to master
- [ ] (optionally) a push of a temporary branch that builds and uploads `Persistence 3.0b1` wheels

**Comment by dataflake** [comment]
Under Python 2.7 and 3.3, the Appveyor Windows compiler believes there's a syntax error. I can't see one in the file.

```
   C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Iinclude -Isrc -Ic:\python27\include -Ic:\python27\PC /Tcsrc\Persistence\_Persistence.c /Fobuild\temp.win32-2.7\Release\src\Persistence\_Persistence.obj
    _Persistence.c
    src\Persistence\_Persistence.c(102) : error C2143: syntax error : missing ';' before 'type'
    src\Persistence\_Persistence.c(104) : error C2065: 's' : undeclared identifier
    src\Persistence\_Persistence.c(104) : error C2109: subscript requires array or pointer type
    src\Persistence\_Persistence.c(104) : error C2065: 's' : undeclared identifier
    src\Persistence\_Persistence.c(104) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
    src\Persistence\_Persistence.c(104) : warning C4024: 'unghost_getattr' : different types for formal and actual parameter 1
    src\Persistence\_Persistence.c(122) : error C2061: syntax error : identifier 'Ptype'
    src\Persistence\_Persistence.c(122) : error C2059: syntax error : ';'
    src\Persistence\_Persistence.c(122) : error C2513: '/*global*/ ' : no variable declared before '='
    src\Persistence\_Persistence.c(170) : error C2065: 'Ptype' : undeclared identifier
    src\Persistence\_Persistence.c(170) : error C2224: left of '.tp_bases' must have struct/union type
    src\Persistence\_Persistence.c(171) : error C2065: 'Ptype' : undeclared identifier
    src\Persistence\_Persistence.c(171) : error C2224: left of '.tp_bases' must have struct/union type
    src\Persistence\_Persistence.c(173) : error C2065: 'Ptype' : undeclared identifier
    src\Persistence\_Persistence.c(173) : error C2224: left of '.tp_base' must have struct/union type
    src\Persistence\_Persistence.c(174) : error C2065: 'Ptype' : undeclared identifier
    src\Persistence\_Persistence.c(174) : error C2224: left of '.tp_basicsize' must have struct/union type
    src\Persistence\_Persistence.c(176) : error C2065: 'Ptype' : undeclared identifier
    src\Persistence\_Persistence.c(178) : error C2065: 'Ptype' : undeclared identifier
    src\Persistence\_Persistence.c(178) : warning C4133: 'function' : incompatible types - from 'int *' to 'PyTypeObject *'
    src\Persistence\_Persistence.c(193) : error C2065: 'Ptype' : undeclared identifier
    error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

**Comment by jamadden** [comment]
Line 102 is `char *s = PyBytes_AS_STRING(as_bytes);` IIRC, that's incompatible with old Visual C compilers (that only support C89 syntax, sigh) because there is code other than variable declarations above it in that function. In old Visual C, [all variable declarations must come at the beginning of a function](https://github.com/libuv/libuv/blob/v1.x/CONTRIBUTING.md#code), before any other code. (Yeah, it's *really* annoying.)

**Comment by dataflake** [comment]
@jamadden Thanks for the explanation. Would it be safe to just reorder the definitions then? Or to be more precise, does ``PyBytes_AS_STRING(as_bytes);`` result in an error condition if ``as_bytes`` is NULL or some other non-True value?

```
@@ -96,11 +96,12 @@ P_getattr(cPersistentObject *self, PyObject *name)
   PyObject *v=NULL;

   PyObject* as_bytes = convert_name(name);
-  if (!as_bytes)
-    return NULL;

   char *s = PyBytes_AS_STRING(as_bytes);

+  if (!as_bytes)
+    return NULL;
+
   if (s[0] != '_' || unghost_getattr(s))
     {
       if (PER_USE(self))
```

**Comment by jamadden** [comment]
`char *s;` needs to be added to the beginning of the function as it was prior to https://github.com/zopefoundation/Persistence/commit/4e94792542287a3edd91a322a57894659ea8bbc0 and then the assignment on the current line can simply be `s = ...`.

**Comment by dataflake** [comment]
Thanks @jamadden commit 0709fbf5fdae40214aaa8c702202ba7624ed7a60 did the trick. All wheels build successfully.
